const campingCarData = [
  {
    id: 1,
    name: "Roadstar",
    image: "./src/assets/Roadstar.jpg",
    price: "2690€",
    Availability: "Disponible",
    LicenseRequired: "Permis B",
  },
  {
    id: 2,
    name: "Adventurer",
    image: "./src/assets/Adventurer.jpg",
    price: "3150€",
    Availability: "Maintenance",
    LicenseRequired: "Permis B",
  },
  {
    id: 3,
    name: "Jayco",
    image: "./src/assets/Jayco.jpg",
    price: "1950€",
    Availability: "Déjà loué",
    LicenseRequired: "Permis B",
  },
  {
    id: 4,
    name: "Odyssey",
    image: "./src/assets/Odyssey.jpg",
    price: "2660€",
    Availability: "Déjà loué",
    LicenseRequired: "Permis Poids Lourd",
  },
  {
    id: 5,
    name: "Freedom",
    image: "./src/assets/Freedom.jpg",
    price: "1950€",
    Availability: "Déjà loué",
    LicenseRequired: "Permis B",
  },
  {
    id: 6,
    name: "Horizon",
    image: "./src/assets/Horizon.jpg",
    price: "2450€",
    Availability: "Déjà loué",
    LicenseRequired: "Permis Poids Lourd",
  },
  {
    id: 7,
    name: "Escape",
    image: "./src/assets/Escape.jpg",
    price: "3450€",
    Availability: "Déjà loué",
    LicenseRequired: "Permis B",
  },
  {
    id: 8,
    name: "Nomad",
    image: "./src/assets/Nomad.jpg",
    price: "2750€",
    Availability: "Déjà loué",
    LicenseRequired: "Permis Poids Lourd",
  },
];

export default campingCarData;
